### ISSUE TITLE
Is there a way to connect to Logstash over HTTP?

### ISSUE THREAD

**Issue by JJ** [bshuster-repo/logrus-logstash-hook#10]
```
tcp: too many colons in address https://listener.logz.io:8071
```

Is there any other way to specify https?

I have been using http and I get this error:

```
Failed to fire hook: write tcp 192.168.1.36:55963->52.21.71.179:8070: write: broken pipe
```

**Comment by ripcurld00d** [comment]
@JJ Thanks for noticing!
I think this is possible using the NewHookWithConn function.
Let me get back to you with that, though.

**Comment by JJ** [comment]
Thanks a lot. I haven't checked out Net::Dial, but it seems to me it's
using only tcp or udp. You'd have to go to Net::HTTP in order to do that.
I'm sorry for bugging you, but I'm trying to use this with logz.io, and
haven't found the way so far. Logz.io has a way of using secure TCP
connection, but it involves a lot of configuration on the client side...

**Comment by ripcurld00d** [comment]
Yes, sure. I know logz.io so there's a good reason to make this hook integrate with their platform.

**Comment by JJ** [comment]
That would be great :-)

**Comment by ripcurld00d** [comment]
@JJ can you give me an example how you send the logs through HTTP(s)?
Do you use a specific HTTP method?
Any detail may be helpful.

Thanks.

**Comment by JJ** [comment]
Code is here:
https://github.com/JJ/CuantoQuedaBot/blob/master/CuantoQuedaBot.go

Definition is line 48, and then I uses normal logrus methods for logging.
It logs to console, but yields an error.

You can use logz.io with http or https, I have tried both.

**Comment by ripcurld00d** [comment]
@JJ thanks for everything. I will be working on this in the following days.
I'll update you when it's done. :hammer:

**Comment by JJ** [comment]
:-) Thanks!

**Comment by ripcurld00d** [comment]
@JJ although I believe we can integrate HTTP to this repository, I think logz.io deserves a repository for its own.
Do you mind using (this hook)[https://github.com/ripcurld00d/logrus-logzio-hook].

**Comment by JJ** [comment]
Thanks for the suggestion :-)

**Comment by ripcurld00d** [comment]
@JJ I am closing this issue.

If you have problems/suggestions, feel free to post them on [logrus-logzio-hook](https://github.com/ripcurld00d/logrus-logzio-hook/issues) repository.

Thanks.

**Comment by JJ** [comment]
Sure, man. Thanks anyway.

**Comment by ripcurld00d** [comment]
Hi @JJ,
Got some good news for you.
To my surprise, Logzio are listening on TCP.

## Use the following snippet
```Go
package main

import (
        "log"

        "github.com/Sirupsen/logrus"
        "github.com/bshuster-repo/logrus-logstash-hook"
)

func main() {
        rus := logrus.New()
        fields := logrus.Fields{"token": "MYTOKEN"}
        hook, err := logrus_logstash.NewHookWithFields("tcp", "listener.logz.io:MYPORT", "app1", fields)
        if err != nil {
                log.Fatal()
        }
        rus.Hooks.Add(hook)
        rus.Info("Test 1")
}

```

## Replace MYTOKEN and MYPORT
* Login to Logzio.
* Go to https://app.logz.io/#/dashboard/data-sources/logstash
* You will find **MYTOKEN** (in this example: abcdeFGHIjKLN1234566) at `Step 1`:
```
mutate {
    add_field => { "token" => "abcdeFGHIjKLN1234566" }
}
```
* The **MYPORT** (in this example: 9292) is mentioned in `Step 2`:
```
tcp {
    host => "listener.logz.io"
    port => 9292
    codec => json_lines
}
```

**Comment by ripcurld0** [comment]
If you're reading this issue and would like to ship logs to logz.io go to https://github.com/bshuster-repo/logruzio
