### ISSUE TITLE
@version should be a string

### ISSUE THREAD

**Issue by stuart-warren** [bshuster-repo/logrus-logstash-hook#13]
Just something I noticed in your readme
The @version field should really be a string:
https://github.com/logstash-plugins/logstash-codec-json/blob/master/spec/codecs/json_spec.rb#L26

**Comment by ripcurld00d** [comment]
I guess [this line](https://github.com/bshuster-repo/logrus-logstash-hook/blob/master/logstash_formatter.go#L32) has to be changed. :cocktail:
