### ISSUE TITLE
Reconnect on connection loss

### ISSUE THREAD

**Issue by drdaeman** [bshuster-repo/logrus-logstash-hook#21]
Sometimes (server restart, intermittent network outages) a TCP connection breaks, and is never restored unless the app is restarted or a hook is recreated anew.

I'd propose implementing automatic reconnections when possible (i.e. persist `protocol` and `address` in `Hook` if they were provided). Easiest solution would be to just re-`Dial` if `h.conn.Write` fails, but since logging is synchronous and starting a TCP connection when the network is down may take a whole minute, it may essentially lock up the caller.

If desirable, I can work on a pull request that'd move network-sending code into a separate goroutine, which would receive data from a buffered channel (or, if introducing a new third-party dependency is acceptable, a [`RingChannel`](https://godoc.org/github.com/eapache/channels#RingChannel)).

What do you think?

**Comment by ripcurld0** [comment]
Hey @drdaeman 🎊 
Thanks for this idea however it looks like it is something out of this hook scope.
I believe you can implement a `net.Conn` that implements `Write(p []byte) (int, error)` in a way that attempts to write and if fails will reconnect to the socket.

Then, what is left to do is to initialize your hook using `NewHookWithConn`.
In case you will write such an implementation, please notify me so I will put a link to it.

Thanks 😃
