### ISSUE TITLE
New API for logrus-logstash-hook

### ISSUE THREAD

**Issue by ripcurld0** [bshuster-repo/logrus-logstash-hook#30]
In the next version (1.xx) I am going to do a major change around the API:

* Deprecate the current logstash formatter in favor of Logrus' JSON Format.
* `WithPrefix`, `WithFields` and `WithField`, `NewHookWithConn` and etc will be removed.
* The Hook structure will be changed.
* Easy way to format and to integrate with Go packages

**Comment by cheshir** [comment]
Hi. Thanks for your work.
When we will be able to use new version of the hook?
