### ISSUE TITLE
case-insensitive import collision

### ISSUE THREAD

**Issue by iwittkau** [bshuster-repo/logrus-logstash-hook#32]
The uppercase "Sirupsen" in this project's import path collides with the lower-case variant.  

When trying to compile on macOS this error occurs:

```
case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
```

I can not switch to an upper-case import path because other hooks I use, use the lower-case variant:

```
cannot use logger (type *"github.com/Sirupsen/logrus".Logger) as type *"github.com/sirupsen/logrus".Logger in assignment
```

**Comment by ripcurld0** [comment]
@iwittkau  
I guess I forgot to import the new package correctly.
I will fix it today.
Thanks

**Comment by warroyo** [comment]
@ripcurld0 I believe that this name change was actually reverted a while back by Sirupsen. SO changing this to lowercase actually is incorrect. can this please be reverted? @iwittkau you may have on old version of `Sirupsen/logrus` the uppercase version is correct

**Comment by ripcurld0** [comment]
@warroyo can you bring any reference to that?
If I search for `logrus` in Github I see the lowercase version.

**Comment by josephfoulds** [comment]
Hey @ripcurld0 please see [relevant](https://github.com/sirupsen/logrus/issues/451#issuecomment-264332021)

**Comment by ripcurld0** [comment]
Hey @josephfoulds 
The comment you have referred was in regard to changing his handle name back to sirupsen.
@sirupsen can you please confirm that?

Thanks.

**Comment by iwittkau** [comment]
There is a section about case-sensivity in the logrus readme:

> The organization's name was changed to lower-case--and this will not be changed back. If you are getting import conflicts due to case sensitivity, please use the lower-case import: `github.com/sirupsen/logrus`.

The change was made 10 days ago. See commit "[readme: add note on casing ](https://github.com/sirupsen/logrus/commit/a9ab54b9d5f3b2e945f9eda26ef0759f3ba3a46e)"

**Comment by sirupsen** [comment]
We need to start converging towards using lower-case everywhere. I apologize we ended up in this situation.

**Comment by ripcurld0** [comment]
@sirupsen thanks a lot for the clarification.
