### ISSUE TITLE
Problem locking package to specific version

### ISSUE THREAD

**Issue by williancarminato** [bshuster-repo/logrus-logstash-hook#34]
I'm having problems to lock this package to a specific version because of the use of branches instead of releases, could you please create releases for them?

As I can see so far we would have `0.2`, `0.3`, `0.4`, `1.0`.

**Comment by ripcurld0** [comment]
@williancarminato thanks. working on this!

**Comment by ripcurld0** [comment]
@williancarminato can you confirm this issue is resolved?

Thanks.

**Comment by williancarminato** [comment]
Hey @ripcurld0 thanks for doing it so fast, it works! Closing the issue 👍
