### ISSUE TITLE
Hook permanently saves all fileds

### ISSUE THREAD

**Issue by flamurey** [bshuster-repo/logrus-logstash-hook#39]
Hi,

Hook and logrus can write logs with different set of fields.
For exmaple,
```
log.WithField("animal", "walrus"}).Info("First log")
log.Info("Second log")
```
Logrus output writes second log without animal field while hook will send log with animal equal to "walrus"

After inspecting hook's code I have found reason for this behavior. copyEntry method save all fields from incoming entry to pool's entry and latest are used in following log events.

Any thoughts about it? Sorry for my bad english.

**Comment by ripcurld0** [comment]
@flamurey thanks for the issue 😸  . Please verify that it was resolved 🙏 .

**Comment by flamurey** [comment]
@ripcurld0 I check issue, it is fixed. Thanks
