### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by boaz1337** [bshuster-repo/logrus-logstash-hook#4]
Need to add unit-tests + functional/integration tests.

**Comment by lpetre** [comment]
Hi @ripcurld00d, I added a simple travis setup, which runs a bunch of go tools and the current set of unit tests. Not sure what functional/integration tests you had in mind.

**Comment by lpetre** [comment]
I looked around at the other logrus hooks tests, most of them assume they can connect to a service and execute the hook logic. I took a look around for how to run logstash within a travis-ci test, but I didn't have much luck. I may look some more tomorrow.

**Comment by JJ** [comment]
Now it's HacktoberFest time, add it as a label to have help coming from that side...

**Comment by ripcurld00d** [comment]
@JJ thanks. :grinning:

**Comment by cheshir** [comment]
@lpetre there is no need to run entire logstash in functional tests. You can emulate it with simple `net.Dial()`.
