### ISSUE TITLE
v0.4 is not working anymore with logrus v1.0.3

### ISSUE THREAD

**Issue by quentin7b** [bshuster-repo/logrus-logstash-hook#44]
This is an informal issue.

Since the [v1.0.3 or loggrus](), the commit [325575f18110626a8fd7f027f899aa8c8f5169c6](https://github.com/sirupsen/logrus/commit/325575f18110626a8fd7f027f899aa8c8f5169c6) makes the [v0.4](https://github.com/bshuster-repo/logrus-logstash-hook/blob/0.4/) to fail because of the dependency of `DefaultTimestampFormat ` [logstash_formatter.go](https://github.com/bshuster-repo/logrus-logstash-hook/blob/0.4/logstash_formatter.go)

Note that the v1.0-beta **is not** impacted by this issue.

**Comment by ripcurld0** [comment]
@quentin7b thanks for that. I will be working on a patch ASAP

**Comment by ripcurld0** [comment]
@quentin7b by the way, why aren't you moving to v1.0?

**Comment by quentin7b** [comment]
@ripcurld0 at this time, the v1.0 is in *beta*... But we already moved to this version ;-).

I just know that some organisations or people don't want to use beta versions and I guess a line in the readme will do the trick for this issue !

**Comment by ripcurld0** [comment]
Sorry it took me that long.

A patch was merged and a release was created.

Colsing 🎉
