### ISSUE TITLE
Not Working with dep

### ISSUE THREAD

**Issue by rendyfebry** [bshuster-repo/logrus-logstash-hook#49]
Master Code and Release source code has different folder stucture

Works with standard go get, but not works with dep

**Comment by ripcurld0** [comment]
@rendyfebry thanks for your report. I will look at it.

**Comment by alihalabyah** [comment]
Any updates?

**Comment by ripcurld** [comment]
@alihalabyah I am really sorry but I am very busy. If someone can take this, I will be very happy.

**Comment by ripcurld** [comment]
I will be working on this. I allocated some time for this in the next 2 weeks.
Sorry for taking it too long. :grinning:

**Comment by ripcurld** [comment]
ping @alihalabyah @rendyfebry 

## Why it fails
OK I think I know what's the problem.
`version`/`release` [1.0-beta](https://github.com/bshuster-repo/logrus-logstash-hook/releases/tag/1.0-beta) is pointing to the master.
While `v0.4.1` which is fetched by `go dep` is an old version of this package but was released to allow users to use the old `logrus-logstash-hook` API with the new `logrus` version.

## Workaround
* Go to `Gopkg.toml` and change the `logrus-logstash-hook` section to:
```
[[constraint]]
  name = "github.com/bshuster-repo/logrus-logstash-hook"
  branch = "master"
  source = "github.com/bshuster-repo/logrus-logstash-hook"
```

* Go to `Gopkg.lock` and change the `logrus-logstash-hook` section to:
```
[[projects]]                                                                                        
  branch = "master"                               
  name = "github.com/bshuster-repo/logrus-logstash-hook"
  packages = ["."]       
  source = "github.com/bshuster-repo/logrus-logstash-hook"
```

## Next release

In next release I am going to solve this problem by allowing the old API and mark it as deprecated.
By doing so, even if you're using old API you can use the latest release.

Thanks.

**Comment by alakotko** [comment]
With new version of dep Gopkg.lock need to be
`[[projects]]
  branch = "master"
  name = "github.com/bshuster-repo/logrus-logstash-hook"
  packages = ["."]
  pruneopts = "UT"
  revision = "1e961e8e173c48bdddbf90e4fc4df8eaf8a7e918"`
