### ISSUE TITLE
Doesn't work on UDP for big messages

### ISSUE THREAD

**Issue by xaionaro** [bshuster-repo/logrus-logstash-hook#51]
It's just a topic for a discussion.

If I try to send a large message then it doesn't fit to MTU. This is from `tcpdump`:
```
10:35:03.216961 IP XXX.XXX.XXX.XXX.55505 > XXX.XXX.XXX.XXX.3535: UDP, bad length 1914 > 1472
```

However it doesn't seems to be the problem of this project. It seems to be a problem of used `net.Conn`… Or UDP just cannot be used for large messages in logstash at all.

So the question: what is the simplest way (if exists) to use this plugin over UDP?

**Comment by boaz1337** [comment]
Hi @xaionaro

Unfortunately, I don't know any good [`net.Conn`](https://golang.org/pkg/net/#Conn) implementation.
Maybe [goautosocket](https://github.com/firstrow/goautosocket) can give a good idea how to implement such a thing for UDP?
