### ISSUE TITLE
set log level

### ISSUE THREAD

**Issue by slifer2015** [bshuster-repo/logrus-logstash-hook#53]
how can i set log level?
for example just error and fatal?

**Comment by boaz0** [comment]
Hi @slifer2015 sorry for the late response.

Right now there is no clean way to do it.
Nevertheless, I think a workaround would be setting a formatter that will return `nil, nil` if the log level is equal to a level you're not desired. By that the writer won't write anything to the socket which ends up with nothing to send to Logstash.

```
func Formatter(e *logrus.Entry) ([]byte, error) {
   if severity, ok := e.Data["level"]; ok && severity == "DEBUG" {
       return nil, nil
   }
   return logrus.JSONFormatter.Format(e)
}
```

Even though, there is no clean API to do so, you're more than welcome to push a PR for adding it.

Again, I'm really sorry for responding late and thanks for your question.
