### ISSUE TITLE
issues with "go modules"

### ISSUE THREAD

**Issue by kbudde** [bshuster-repo/logrus-logstash-hook#54]
Hi,

I've tried to convert my project to go modules.
By default the last release 0.41.0is chosen which is from 2017 and quite older than master.

I think it would be wise to create a new release from time to time.

Current workaround:

    Update you go.mod file to use the master branch instead of version.

**Comment by 0987363** [comment]
If you use go mod, use this
GO111MODULE=on go get github.com/bshuster-repo/logrus-logstash-hook@master

It will update logrus-logstash-hook to master branch with go.mod and go.sum.

**Comment by Alex-liutao** [comment]
having the same issue here, I'll really appreciate it if 1.0.0 version release

**Comment by boaz0** [comment]
@Alex-liutao - sorry for not updating this package for awhile.
I will take care of it this week and release v1.0.
Thanks for your input.

**Comment by yads** [comment]
@boaz0 do you think you'd have time to publish the v1.0 release?

**Comment by boaz0** [comment]
@yads I thought I did [here](https://github.com/bshuster-repo/logrus-logstash-hook/releases/tag/v1.0)

**Comment by yads** [comment]
That's odd. I see that it exists, but when I did a `go build` it only pulled down 0.4.1. I'll see if I can explicitly pull down 1.0.

**Comment by boaz0** [comment]
Yep, I have no idea why it keeps pulling 0.4.1. Let me know if setting explicitly it to 1.0 works.

**Comment by yads** [comment]
@boaz0 So I believe the issue is actually that `1.0` does not follow semantic versioning as it does not have a patch number. Because you can only point a go module at `1.0.0` it is unable to find the `1.0` tag. See the 'Semantic versions and modules' section here https://blog.golang.org/publishing-go-modules

**Comment by boaz0** [comment]
@yads thanks for that! I changed the version to `1.0.0` as you suggested.
Feel free to check it out.

**Comment by yads** [comment]
Woot, it's working now! Thanks for such a quick turnaround.

**Comment by boaz0** [comment]
@yads no problems. I am glad we got this fixed. I was struggling for weeks why it did not work and thought maybe it is just on my machine but you did an amazing job and figure it out.

Thank you so much!
