### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by janekolszak** [bshuster-repo/logrus-logstash-hook#57]
Hi,
We need a new release to fix the bug with persistent fields added with WithField method

Thanks! :)

**Comment by boaz0** [comment]
Hi @janekolszak 
The stable release doesn't support `WithField` methods. Nevertheless, version 0.4.1 is supporting it and available ([branch 0.4](https://github.com/bshuster-repo/logrus-logstash-hook/tree/0.4))

If you still want to use the stable release, instead of doing:

```golang
hook, err := logrustash.NewHookWithFields("tcp", "172.17.0.2:9999", "myappName", logrus.Fields{})

hook.WithFields(logrus.Fields{
        "hostname":    os.Hostname(),
        "serviceName": "myServiceName",
})
```

```golang
log := logrus.New()
conn, err := net.Dial("tcp", "logstash.mycompany.net:8911")
if err != nil {
    log.Fatal(err)
}
hook := logrustash.New(conn, logrustash.DefaultFormatter(logrus.Fields{"type": "myappName"}))

log.Hooks.Add(hook)
ctx := log.WithFields(logrus.Fields{
        "hostname":    os.Hostname(),
        "serviceName": "myServiceName",
})
```

**Comment by choppedpork** [comment]
@boaz0 `logrustash.DefaultFormatter` is not actually present in v0.4.1 - I got bitten by this when moving to Go 1.13 + modules as the module system by default uses the latest release which, as opposed to master, does not have the DefaultFormatter. Would be great to see a new release!

In the meantime `go get github.com/bshuster-repo/logrus-logstash-hook@b3d898b5138adbc4c4da62fa6d889f18a587566b` has done the trick for me :)

**Comment by boaz0** [comment]
That's true, because master has the new API.
I guess I should mention that in the README.md file.

Thanks for the feedback though.

**Comment by boaz0** [comment]
I am closing this as the master branch was released [here](https://github.com/bshuster-repo/logrus-logstash-hook/releases/tag/1.0).

If there is a problem with this, feel free to re-open this.

Thanks.
