### ISSUE TITLE
Test error with Go 1.14beta1

### ISSUE THREAD

**Issue by eclipseo** [bshuster-repo/logrus-logstash-hook#58]
Fedora Rawhide, with Go 1.14beta1, logrus-logstash-hook 0.4.1

```
Testing    in: /builddir/build/BUILD/logrus-logstash-hook-0.4.1/_build/src
         PATH: /builddir/build/BUILD/logrus-logstash-hook-0.4.1/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/logrus-logstash-hook-0.4.1/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags "-X github.com/bshuster-repo/logrus-logstash-hook/version=0.4.1 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '"
      testing: github.com/bshuster-repo/logrus-logstash-hook
github.com/bshuster-repo/logrus-logstash-hook
--- FAIL: TestLogstashFormatter (0.00s)
    logstash_formatter_test.go:58: expected data[error] to be 'Get http://example.com: The error' but got 'Get "http://example.com": The error'
FAIL
```
Seem like the formatting changed slightly to include quotes.

**Comment by eclipseo** [comment]
See https://github.com/golang/go/commit/64cfe9fe22113cd6bc05a2c5d0cbe872b1b57860#diff-9667474d33400190658e4758cf28dbf5
and
https://github.com/golang/go/issues/29261

**Comment by boaz0** [comment]
Hey @eclipseo :wave: It seems like an easy fix, would you mind working on it?
If it's too much work for you, I will try to push a fix in the next days.

Sorry for the late response and thanks for looking into it.

**Comment by boaz0** [comment]
@eclipseo - I looked at it and I decided that version 0.4.1 is going to support only old versions of Go (up to Go 1.12).
I am releasing a new release (0.5) that supports new versions of Go.

**Comment by eclipseo** [comment]
Hey sorry for the delay. I've built 1.0.0 with Go 1.15 beta 1 and everything works fine.

**Comment by boaz0** [comment]
Thanks @eclipseo for the update.
I am sorry for taking me too long fixing it. I hope next time I will do a better and faster job.
