### ISSUE TITLE
README on master out of date

### ISSUE THREAD

**Issue by mhcassiem** [bshuster-repo/logrus-logstash-hook#59]
This was a bit annoying but I found that the README that displays on github is out of date, the README found in vendor/github/bshuster-repo/logrus-logstash-hook is up to date however. 

Its not wholly intuitive for someone to check the vendor files for help on installed packages.

**Comment by boaz0** [comment]
Hey there @mhcassiem :wave: 

What vendor directory are you talking to?

Sorry for that and I would like to make it work but first I need where I can get that /vendor/github/bshuster-repo/logrus-logstash-hook README?

Because maybe the vendor is using an old version.

Thanks.

**Comment by mhcassiem** [comment]
Sorry,

I'm not wholly clued up on the appropriate jargon. By vendor folder, I was
speaking about the folder under which all my Go packages for my project are
installed to. I don't think its an old README that's being used when the
package installed because after following that README I was able to add
hooks to my logrus logger. logrustash.New() doesn't exist in the package I
installed.

I hope that made sense.

Kind Regards

Muhammad Haaroon Cassiem

**Comment by mhcassiem** [comment]
Its actually the fact that the last release was in September 2017 and the
README (and I'm assuming the whole repo) was updated sooner than that. So
anyone who's using logrustash will be getting the old release of September
2017 in the Golang applications.

Kind Regards

Muhammad Haaroon Cassiem

**Comment by boaz0** [comment]
So @mhcassiem it seems like you're using 0.4 version which is not master.
You can read the README file here: https://github.com/bshuster-repo/logrus-logstash-hook/tree/0.4

You're welcome to get the updated version (master) of this package using your go package manager.

Hope it helped.

**Comment by mhcassiem** [comment]
It did, I had to add an override in my toml file. Pointing to master now.

I think the issue arose because I let my IDE sort out the package
installation rather than explicitly dep ensuring it, for some reason it
defaulted to latest release. Thanks for the assist, I'll delete that issue.

Kind Regards

Muhammad Haaroon Cassiem

**Comment by boaz0** [comment]
Hey @mhcassiem,

I am letting you know, the master branch has been released [here](https://github.com/bshuster-repo/logrus-logstash-hook/releases/tag/1.0).

I am also closing this ticket, but if there is anything wrong, feel free to re-open it.

Thanks.
