### ISSUE TITLE
confusing versioning: 1.0 or 0.5 or 5.0?

### ISSUE THREAD

**Issue by onlyjob** [bshuster-repo/logrus-logstash-hook#61]
Why the single commit b3d898b is tagged as __1.0__, __0.5-beta__, __v5.0__, __v1.0__ and __v0.5__ _at the same time_??

This is very confusing.

**Comment by boaz0** [comment]
Yeah, that's my fault. I don't know how to delete that 0.5 and 5.0 tags... :confused:

**Comment by onlyjob** [comment]
Try the following:

```
git tag --delete "tagname"
git push --delete origin "tagname"
```

**Comment by boaz0** [comment]
Thanks. I think it works. Can you confirm this? :smile:

**Comment by onlyjob** [comment]
Definitely worked: https://github.com/bshuster-repo/logrus-logstash-hook/releases

All good, thanks!

**Comment by boaz0** [comment]
Thank you for your help and time @onlyjob
