### ISSUE TITLE
timestamp in Unix format

### ISSUE THREAD

**Issue by bolshoydi** [bshuster-repo/logrus-logstash-hook#64]
How to change timestamp format from `string` to Unix format `float64` or `int64` ??
by default it gives `"@timestamp" => "2016-02-29T16:57:23.000Z",`
I want to pass time as Unix time `"@timestamp" => 1611664414.310306`. 
And if it possible to leave `time` as is in `time.RFC3339` format. 
e.g. outgoing message should be like this
```json
{
  "@level": "info",
  "@message": "Init logger with Logstash!",
  "time": "2021-01-26T19:10:59+03:00",
  "@timestamp": 1611677459.123
}
```
The only thing I succeed in is that I can add such timestamp in extra fields.
```go
hook := logrustash.New(conn, logrustash.DefaultFormatter(logrus.Fields{"hostname": "my_sginy_host", "@timestamp":time.Now().Unix()}))
logger.Hooks.Add(hook)
```
Such code adds `@timestamp` in the `fields` section.
```json
{
  "@timestamp": "2021-01-26T19:10:59+03:00",
  "@version":"1",
  "fields.@timestamp": 1611677459,
  "hostname": "my_shiny_host",
  "@level": "info",
  "message": "Init.redis!", "type":"log"
}
```

**Comment by boaz0** [comment]
Hi @bolshoydi 
Sorry for the late response.
In regard to your question I have good and bad news.
The good news it is possible to do it, the bad news it requires some changes on your side.

By default, [DefaultFormatter](https://github.com/bshuster-repo/logrus-logstash-hook/blob/master/hook.go#L105-L116) is used by default.

In other words, you will have to configure your own formatter in the following way 
```
	formatter := logrustash.LogstashFormatter{
		Formatter: &logrus.JSONFormatter{
			FieldMap: logrus.FieldMap{
				logrus.FieldKeyTime: "__timestamp",
				logrus.FieldKeyMsg:  "message",
			},
		},
	}
        hook := logrustash.New(writer, formatter)
        log.Hooks.Add(hook)
        ctx := log.WithFields(logrus.Fields{
                "@timestamp": time.Now().Unix(),
        })
```

I am closing this issue as I hope this was helpful.
