### ISSUE TITLE
nothing written to logstash!

### ISSUE THREAD

**Issue by mohammadinasab-dev** [bshuster-repo/logrus-logstash-hook#69]
Hello,

I'm testing your library just like your example but nothing written in LogStash/Elasticsearch until I add a one second time delay before the program ended!
here the code it is:

```
func main() {
	log := logrus.New()
	conn, err := net.Dial("tcp", "127.0.0.1:8911")
	if err != nil || conn == nil {
		log.Fatal(err)
	}
	hook := logrustash.New(conn, logrustash.DefaultFormatter(logrus.Fields{"type": "myappName"}))

	log.Hooks.Add(hook)
	ctx := log.WithFields(logrus.Fields{
		"method": "main",
	})
	ctx.Info("Hello World in print again!")

	time.Sleep(1 * time.Second)
}
```

I'll appreciate if anybody can help

**Comment by boaz0** [comment]
Hi :wave: @mohammadinasab-dev 

Can you attach Logstash configuration.

**Comment by mohammadinasab-dev** [comment]
@boaz0 

```
input{
    tcp{
       host => "127.0.0.1"
       port => 8911
       mode => server
       codec => json
    }
}

filter{
    json{
        source => "message"
    }
}
output{
    elasticsearch{
	hosts => "http://localhost:9200/"
	index => "j-06-json"
    }
}
```

**Comment by boaz0** [comment]
Hi @mohammadinasab-dev I was trying to reproduce this bug but unfortunately I can not.

This is what I get:

```
{"@version":"1","level":"info","method":"main","type":"myappName","host":"localhost","message":"Hello World in print again!","@timestamp":"2021-06-21T16:23:58.000Z"}
```

**Comment by mohammadinasab-dev** [comment]
@boaz0 
thank you again,
i'm at windows and i use CMD to run logstash (ELK)

**Comment by boaz0** [comment]
@mohammadinasab-dev maybe that's the problem.
I am running Linux and even without the `time.Sleep` I can see the logs.

Can you try to do

```go
func main() {
	log := logrus.New()
	conn, err := net.Dial("tcp", "127.0.0.1:8911")
	if err != nil || conn == nil {
		log.Fatal(err)
	}
	hook := logrustash.New(conn, logrustash.DefaultFormatter(logrus.Fields{"type": "myappName"}))

	log.Hooks.Add(hook)
	ctx := log.WithFields(logrus.Fields{
		"method": "main",
	})
        for i := 0; i < 10; i++ {
            ctx.Info("Hello ", i)
        }
}
```

Do you see any logs and how many lines?

**Comment by mohammadinasab-dev** [comment]
@boaz0 yes maybe the windows is the problem!
it work as explain below:
i try your code many times and after 2nd or 3rd i have all 10 in both stdout and ES too!
and at the first time nothing then at the second time 9 and for 3rd tries and more i have exactly 10!

**Comment by shojaeix** [comment]
Hi @mohammadinasab-dev 
Can you put a `log.Exit(1)` at the end of your `main` function and see if it makes any difference?

**Comment by mohammadinasab-dev** [comment]
Hi @shojaeix and thanks for your attention
yes i did and nothing changes, just it works correct in for loop, or running the program fast and continuously for many times(it looks like a manual looping!).

**Comment by shojaeix** [comment]
> Hi @shojaeix and thanks for your attention
> yes i did and nothing changes, just it works correct in for loop, or running the program fast and continuously for many times(it looks like a manual looping!).
> am i correct by your mean?
> ‍‍‍‍````
> func main() {
> log := logrus.New()
> conn, err := net.Dial("tcp", "127.0.0.1:8911")
> if err != nil || conn == nil {
> log.Fatal(err)
> }
> hook := logrustash.New(conn, logrustash.DefaultFormatter(logrus.Fields{"type": "myappName"}))
> 
> 
> log.Hooks.Add(hook)
> ctx := log.WithFields(logrus.Fields{
> 	"method": "main",
> })
> // for i := 0; i < 10; i++ {
> // 	ctx.Info("Hello", i)
> // }
> ctx.Info("hello")
> log.Exit(1)
> ````
> 
> }

I though this function will wait and write all logs before exiting.

**Comment by boaz0** [comment]
@mohammadinasab-dev I believe this is probably a non-deterministic behavior on behalf of Go.
Would you mind opening a ticket on Go repository and see what they think?

Thanks.

**Comment by mohammadinasab-dev** [comment]
@shojaeix it seems to be, but it wasn't wait!!

**Comment by mohammadinasab-dev** [comment]
@boaz0 my go version is 1.15.2 maybe i should upgrade it to latest, and a ticket on go repository is good idea, anyway thank you again .

**Comment by boaz0** [comment]
You're welcome. I will colse this issue but feel free to re-open it if you disagree.

Let me know if there is any update. I would like to know what was the problem and how this plugin can help with this.

Thanks.
