### ISSUE TITLE
Timestamp accuracy

### ISSUE THREAD

**Issue by trinode** [bshuster-repo/logrus-logstash-hook#70]
Hi there,

I've set up this hook, and the timestamps are at whole second intervals, so sorting on the timestamps where there are more than 1 per second is somewhat broken.

for the console logs that come out of logrus I was able to get accurate timestamps like this:

```
log := logrus.New()
	fmt := new(logrus.TextFormatter)
	fmt.TimestampFormat = time.RFC3339Nano
	fmt.FullTimestamp = true
	log.SetFormatter(fmt)
```

for this hook though I'm unable to figure out how to get more accurate timestamps
This is the console:
![image](https://user-images.githubusercontent.com/965926/123674003-06938a00-d839-11eb-9c21-7948efc0d1c5.png)
This is kibana, sorted by timestamp (out of order):
![image](https://user-images.githubusercontent.com/965926/123674260-51ad9d00-d839-11eb-9087-97c15ffe22c3.png)

Is there a way around this?

**Comment by boaz0** [comment]
Thank @trinode for this ticket.
I am going to look at it in the next days.

**Comment by trinode** [comment]
Thanks for the quick reply, 

I got it working by copying and pasting bits of the hook out into my app so I could access what I needed (not ideal but might help you see what we'd want to be able to configure):

```
	logstashFieldMap := logrus.FieldMap{
		logrus.FieldKeyTime: "@timestamp",
		logrus.FieldKeyMsg:  "message",
	}
        
	fields := logrus.Fields{"@version": "1", "type": "log", "app": "lookout", "environment": env}

	fmt2 := new(logrus.JSONFormatter)
	fmt2.TimestampFormat = time.RFC3339Nano
	fmt2.FieldMap = logstashFieldMap

	formatter := logrustash.LogstashFormatter{
		Formatter: fmt2,
		Fields:    fields,
	}

	hook := logrustash.New(conn, formatter)

	log.Hooks.Add(hook)

```
