### ISSUE TITLE
how to reconnect to logstash when logstash server resart or no-write long time

### ISSUE THREAD

**Issue by windzhu0514** [bshuster-repo/logrus-logstash-hook#76]
how to reconnect to logstash when logstash server resart or no-write long time

**Comment by boaz0** [comment]
@windzhu0514 sorry for the late response.
Although you closed it, I just want to make sure you know it's possible with the help of external libraries.
You can read more [here](https://github.com/bshuster-repo/logrus-logstash-hook/issues/48#issuecomment-361938249)
